spring:
  datasource:
    url:  jdbc:mysql://10.45.53.110:3306/lottery?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ztesoft
  redis:
    host: 10.45.53.111
    port: 6379
    password:
    database: 1
    timeout: 1000
    jedis:
      pool:
        max-active: 8000
        max-wait: 5000
        max-idle: 500

redisson:
  address: redis://10.45.53.111:6379

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.iwhalecloud.lottery.pojo
